pipeline: install missing libdbus
```
Failed to build dbus-python
[...]
checking for gcc... gcc
[...]
checking for DBUS... no
configure: error: Package requirements (dbus-1 >= 1.8) were not met:

No package 'dbus-1' found

[...]
subprocess.CalledProcessError: Command '['/tmp/pip-install-f00ksv7b/dbus-python/configure', '--disable-maintainer-mode', 'PYTHON=/home/runner/.local/share/virtualenvs/systemctl-mqtt-UQbfQXT6/bin/python', '--prefix=/tmp/pip-install-f00ksv7b/dbus-python/build/temp.linux-x86_64-3.8/prefix']' returned non-zero exit status 1.
```